### ISSUE TITLE
reward can potentially be zero in _getREward

### ISSUE THREAD

**Issue by storming0x** [yearn/veYfi#34]
Here if the account has no ve locked and we are using getRewardFor or getReward()
https://github.com/yearn/veYfi/blob/d42be4f6cbad7dd936d8b461a4c6cd5e4bddd61a/contracts/VeYfiRewards.sol#L144

Potentially it can have zero rewards, so later in approve or transfers we are sending 0 as amount, guessing it reverts downstream.

**Comment by pandadefi** [comment]
that would be a bit stupid to call claim rewards without any gains. I have made this a return
https://github.com/yearn/veYfi/commit/df64cc5a5ab1df163fc67b7057dedafd2b7ee722

But maybe it should be a `require` ?

**Comment by anticlimactic** [comment]
trying to understand why this is an issue better: is the idea that because zero is typically an edge case, and `_getReward` calls other functions (i.e. `veToken.deposit_for`) and therefore may incidentally trigger a revert/require downstream?

in contrast, in this case (`donate` function from same file), the require check on zero is optional as the function only calls one function: `safeTransferFrom`, which allows a zero transfer (but this is used to save gas or some other reason?)

```
function donate(uint256 _amount) external returns (bool) {
    require(_amount != 0, "==0");
    IERC20(rewardToken).safeTransferFrom(
        msg.sender,
        address(this),
        _amount
    );
    queuedRewards = queuedRewards + _amount;
    return true;
}
```

**Comment by pandadefi** [comment]
>[](https://github.com/yearn/veYfi/issues/34#issuecomment-1047482666)trying to understand why this is an issue better: is the idea that because zero is typically an edge case, and _getReward calls other functions (i.e. veToken.deposit_for) and therefore may incidentally trigger a revert/require downstream?
Yes

**Comment by storming0x** [comment]
> But maybe it should be a `require` ?

Yeah potentially since it could return 0, but no event was emitted and here and other places:
